## 1. Библиотека numpy. Вычислительные задачи

### Задание 1

Создайте numpy array с элементами от числа N до 0. Например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

## 1. Numpy library. Computational tasks

### Task 1

Create a numpy array with elements from the number N to 0. For example, for N = 10 it will be an array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
def my_array(N):
    x = np.arange(0,N)
    return np.flip(x,0)
    #np.sort(np.arange(0, N))[::-1]
    #return np.arange(N-1,-1,-1)
print(my_array(10))
print(my_array(15))
print(my_array(20))

[9 8 7 6 5 4 3 2 1 0]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

### Task 2

Create a diagonal matrix with elements from N to 0. Calculate the sum of its values on the diagonal.

In [3]:
def sum_matrix(N):
    my_matrix = np.diag(np.flip(np.arange(N,0,-1)))
    return np.trace(my_matrix)
 
print(sum_matrix(5))
print(sum_matrix(10))
print(sum_matrix(15))

15
55
120


### Задание 3

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем
Матрица в виде numpy array

На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
    
Найдите индекс самого похожего пользователя max_index, т.е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.
Нумерацию индексов следует начинать с 0  

### Task 3

There is a matrix of purchases in the online store. Column A is the user ID. The remaining columns are the number of purchases of product categories by this user
A matrix in the form of a numpy array

Another visitor comes to the site, about whose purchases the following is known:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Find the index of the most similar user max_index, i.e. calculate the cosine similarity between this user and all users from the user_stats array.
Index numbering should start from 0

In [4]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

next_user_length = np.linalg.norm(next_user_stats)
cosine_convergence = []

for user in users_stats:
    old_user_length = np.linalg.norm(user)
    cosinus = np.dot(next_user_stats,user) / (next_user_length*old_user_length)
    cosine_convergence.append(cosinus)

print(cosine_convergence.index(max(cosine_convergence)))

7


![](Numpy_log.png)